# Generated by Django 5.0.6 on 2024-06-27 03:23

import django.contrib.auth.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Game_name', models.CharField(max_length=200)),
                ('pic1', models.FileField(null=True, upload_to='product_images')),
            ],
        ),
        migrations.CreateModel(
            name='MyCustomUser',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.CharField(max_length=15)),
                ('store_name', models.CharField(max_length=200, null=True)),
                ('store_location', models.CharField(max_length=300, null=True)),
                ('city', models.CharField(max_length=100, null=True)),
                ('area', models.CharField(max_length=100, null=True)),
                ('user_type', models.CharField(max_length=20)),
                ('verifi', models.CharField(max_length=100, null=True)),
                ('wallet', models.IntegerField(null=True)),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='add_games',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_game', models.CharField(max_length=15)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='biillardsgamme_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datte', models.CharField(max_length=100)),
                ('number_of_billiards', models.CharField(max_length=100)),
                ('in_time', models.CharField(max_length=100)),
                ('out_time', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('store_location', models.CharField(max_length=300)),
                ('mins', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('booking_id', models.CharField(max_length=100)),
                ('time_of_booking', models.CharField(max_length=100)),
                ('book_sta', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BilliardsGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_billiards', models.IntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BowlingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_billiards', models.IntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BowlingGame_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datte', models.CharField(max_length=100)),
                ('number_of_billiards', models.CharField(max_length=100)),
                ('in_time', models.CharField(max_length=100)),
                ('out_time', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('store_location', models.CharField(max_length=300)),
                ('mins', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('booking_id', models.CharField(max_length=100)),
                ('time_of_booking', models.CharField(max_length=100)),
                ('book_sta', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='kidsgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pcgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_ps_device', models.IntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='pcgame_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datte', models.CharField(max_length=100)),
                ('number_of_billiards', models.CharField(max_length=100)),
                ('in_time', models.CharField(max_length=100)),
                ('out_time', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('store_location', models.CharField(max_length=300)),
                ('mins', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('booking_id', models.CharField(max_length=100)),
                ('time_of_booking', models.CharField(max_length=100)),
                ('book_sta', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='psgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_ps_device', models.IntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='psgame_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datte', models.CharField(max_length=100)),
                ('number_of_billiards', models.CharField(max_length=100)),
                ('in_time', models.CharField(max_length=100)),
                ('out_time', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('store_location', models.CharField(max_length=300)),
                ('mins', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('booking_id', models.CharField(max_length=100)),
                ('time_of_booking', models.CharField(max_length=100)),
                ('book_sta', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Snookergame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_snooker', models.IntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Snookergame_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datte', models.CharField(max_length=100)),
                ('number_of_billiards', models.CharField(max_length=100)),
                ('in_time', models.CharField(max_length=100)),
                ('out_time', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('store_location', models.CharField(max_length=300)),
                ('mins', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('booking_id', models.CharField(max_length=100)),
                ('time_of_booking', models.CharField(max_length=100)),
                ('book_sta', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='store_image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.FileField(null=True, upload_to='uploads')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=150)),
                ('amount', models.IntegerField()),
                ('payment_verification', models.CharField(max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vrgame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_of_vr_device', models.IntegerField()),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Vrgame_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datte', models.CharField(max_length=100)),
                ('number_of_billiards', models.CharField(max_length=100)),
                ('in_time', models.CharField(max_length=100)),
                ('out_time', models.CharField(max_length=100)),
                ('store_name', models.CharField(max_length=100)),
                ('store_location', models.CharField(max_length=300)),
                ('mins', models.CharField(max_length=100)),
                ('cost', models.CharField(max_length=100)),
                ('booking_id', models.CharField(max_length=100)),
                ('time_of_booking', models.CharField(max_length=100)),
                ('book_sta', models.CharField(max_length=20)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
